### ISSUE TITLE
W widoku desktop nie ma poziomki 

### ISSUE THREAD

**Issue by adamskrodzki** [Ziomeka/agnieszkaziomek#9]
![image](https://user-images.githubusercontent.com/10146412/47621955-48575a00-daff-11e8-9b1f-01f4e0d95dfe.png)

**Comment by adamskrodzki** [comment]
@Ziomeka do poprawki

**Comment by Ziomeka** [comment]
Thank you for noticing it. Fixed with web.config ajustment.
